services:
  ml_metrics_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mlops
      - POSTGRES_PASSWORD=${ML_METRICS_DB_PASSWORD:-uTcdEf43}
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - "${ML_METRICS_DB_SCHEMA_DIR:-../../analytics/ml-monitoring/metrics/schemas/}:/docker-entrypoint-initdb.d/"
  prefect_server:
    image: prefecthq/prefect:2.11.4-python3.8
    entrypoint:
      [
        "/opt/prefect/entrypoint.sh",
        "prefect",
        "server",
        "start"
      ]
    environment:
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    expose:
      - 4200
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import requests; requests.get('http://localhost:4200').raise_for_status()"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - ${PREFECT_SERVER_HOST_PORT:-4200}:4200
    profiles:
      - prefect
